from . import (
    fund,
    salary_rate,
    setting,
    tariff,
    # payment_batch,
    # payment,
    # payout,
    # cash_entry,
    # fund_due,
    property_tax,
    user,
    receipt_scan,
    receipt,
    loan,
    project,
    transaction,
    due_note,
    wallet,
    asset,
    asset_manager,
    wallet_transfer,
)
from .dashboards import registry as _dashboard_registry  # noqa: F401 — import for side-effects (URL + sidebar registration)
