# Generated by Django 6.0.7 on 2026-08-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0048_transaction_is_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_blur',
            field=models.BooleanField(default=False, help_text='Permanently hide the balance/in/out figures'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=10),
        ),
    ]
