# Generated by Django 6.0.7 on 2026-08-06 22:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0049_wallet_is_blur_alter_transaction_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('nominal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=15)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_direct_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fee.transaction')),
                ('income_transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fee.transaction')),
                ('user', models.ForeignKey(help_text='Resident who paid directly — becomes the user on both the IN and OUT leg.', on_delete=django.db.models.deletion.PROTECT, related_name='direct_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direct_expenses',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='direct_expense',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='fee.directexpense'),
        ),
    ]
