# Generated by Django 6.0.7 on 2026-08-07 07:24

import ql.fee.models.receipt
import ql.fee.services.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0050_directexpense_transaction_direct_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=ql.fee.models.receipt.ReceiptImageField(blank=True, null=True, storage=ql.fee.services.storage.get_receipt_storage, upload_to=ql.fee.models.receipt._receipt_upload_to),
        ),
    ]
