# Generated by Django 6.0.7 on 2026-08-07 07:35

import ql.fee.models.asset
import ql.fee.models.due_note
import ql.fee.models.receipt
import ql.fee.services.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0050_directexpense_transaction_direct_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='receipt_storage',
            field=models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', editable=False, help_text='Backend that holds the asset file.', max_length=10),
        ),
        migrations.AddField(
            model_name='duenoteproof',
            name='receipt_storage',
            field=models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', editable=False, help_text='Backend that holds the proof image.', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=ql.fee.services.storage.DynamicStorageFileField(blank=True, null=True, storage=ql.fee.services.storage.get_asset_storage, upload_to=ql.fee.models.asset._asset_upload_to),
        ),
        migrations.AlterField(
            model_name='duenoteproof',
            name='image',
            field=ql.fee.services.storage.DynamicStorageImageField(storage=ql.fee.services.storage.get_receipt_storage, upload_to=ql.fee.models.due_note._due_note_proof_upload_to),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=ql.fee.services.storage.DynamicStorageImageField(blank=True, null=True, storage=ql.fee.services.storage.get_receipt_storage, upload_to=ql.fee.models.receipt._receipt_upload_to),
        ),
    ]
