# Generated by Django 6.0.7 on 2026-08-21 18:13

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CONCURRENTLY can't run inside a transaction.
    atomic = False

    dependencies = [
        ('fee', '0052_rename_receipt_storage_to_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='transaction',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['-occurred_at', '-created_at', '-id'], name='transactions_active_order_idx'),
        ),
    ]
