# Generated by Django 6.0.7 on 2026-08-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0053_transaction_transactions_active_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='processing_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='ready', max_length=10),
        ),
    ]
