# Generated by Django 6.0.7 on 2026-08-24 04:58

import ql.fee.models.asset
import ql.fee.services.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0054_asset_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='thumbnail',
            field=ql.fee.services.storage.DynamicStorageFileField(blank=True, null=True, storage=ql.fee.services.storage.get_asset_storage, upload_to=ql.fee.models.asset._asset_thumbnail_upload_to),
        ),
    ]
