# Generated by Django 6.0.7 on 2026-09-07 10:31

import django.db.models.deletion
import ql.fee.models.wallet_transfer_receipt
import ql.fee.services.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0055_asset_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransferReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('image', ql.fee.services.storage.DynamicStorageImageField(blank=True, null=True, storage=ql.fee.services.storage.get_receipt_storage, upload_to=ql.fee.models.wallet_transfer_receipt._receipt_upload_to)),
                ('storage', models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', editable=False, help_text='Backend that holds the receipt file.', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfer_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transfer_receipts',
            },
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='fee.wallettransferreceipt'),
        ),
    ]
