# Generated by Django 6.0.7 on 2026-10-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0056_wallettransferreceipt_wallettransfer_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_pass_through',
            field=models.BooleanField(default=False, help_text='Money collected is handed over as-is (e.g. garbage collector pay). Payouts are tracked per period on the Garbage Payouts page.'),
        ),
        migrations.CreateModel(
            name='RoutinePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='fee.transactionitem')),
            ],
            options={
                'db_table': 'routine_payouts',
                'ordering': ['period', 'created_at'],
                'indexes': [models.Index(fields=['period'], name='routine_pay_period_7dba9f_idx')],
            },
        ),
    ]
