# Generated by Django 6.0.6 on 2026-06-26 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(choices=[('SECURITY', 'Security Guard')], default='SECURITY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_from', models.DateField()),
                ('end_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_from'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('GENERAL', 'General (Kas RT)'), ('GARBAGE', 'Garbage (pass-through)'), ('EARMARKED', 'Earmarked')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'GENERAL')), fields=('kind',), name='fund_unique_general'), models.UniqueConstraint(condition=models.Q(('kind', 'GARBAGE')), fields=('kind',), name='fund_unique_garbage')],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MONTHLY', 'Monthly iuran'), ('GARBAGE', 'Garbage iuran')], max_length=10)),
                ('period', models.CharField(max_length=7)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ql.paymentbatch')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(choices=[('SECURITY', 'Security Guard'), ('SANITATION', 'Sanitation Worker')], max_length=20)),
                ('period', models.CharField(max_length=7)),
                ('payout_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payout_date', 'payee'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MONTHLY', 'Monthly iuran'), ('GARBAGE', 'Garbage iuran')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_from', models.DateField()),
                ('end_to', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'kind', 'start_from'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Contributor for IN; responsible person for OUT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_entries', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ql.fund')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['fund', 'direction'], name='ql_cashentr_fund_id_a847d9_idx'), models.Index(fields=['occurred_at'], name='ql_cashentr_occurre_ade5d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FundDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dues', to='ql.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fund', 'user'), name='fund_dues_unique_fund_user')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['user'], name='ql_paymentb_user_id_43c853_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['paid_at'], name='ql_paymentb_paid_at_46dc38_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['kind', 'period'], name='ql_payment_kind_25044a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['batch'], name='ql_payment_batch_i_88cfab_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payee', 'period'], name='ql_payout_payee_2781c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['payout_date'], name='ql_payout_payout__9439d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['user', 'kind'], name='ql_tariff_user_id_4d7337_idx'),
        ),
    ]
