# Generated by Django 6.0.6 on 2026-07-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashentry',
            new_name='cash_entrie_fund_id_53125c_idx',
            old_name='ql_cashentr_fund_id_a847d9_idx',
        ),
        migrations.RenameIndex(
            model_name='cashentry',
            new_name='cash_entrie_occurre_f6ad31_idx',
            old_name='ql_cashentr_occurre_ade5d3_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_kind_f680c2_idx',
            old_name='ql_payment_kind_25044a_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_batch_i_1122a3_idx',
            old_name='ql_payment_batch_i_88cfab_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentbatch',
            new_name='payment_bat_user_id_e764fd_idx',
            old_name='ql_paymentb_user_id_43c853_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentbatch',
            new_name='payment_bat_paid_at_c3564f_idx',
            old_name='ql_paymentb_paid_at_46dc38_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_payee_cb184e_idx',
            old_name='ql_payout_payee_2781c6_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_payout__5e6bee_idx',
            old_name='ql_payout_payout__9439d6_idx',
        ),
        migrations.RenameIndex(
            model_name='tariff',
            new_name='tariffs_user_id_7378e3_idx',
            old_name='ql_tariff_user_id_4d7337_idx',
        ),
        migrations.AlterModelTable(
            name='cashentry',
            table='cash_entries',
        ),
        migrations.AlterModelTable(
            name='fund',
            table='funds',
        ),
        migrations.AlterModelTable(
            name='funddue',
            table='fund_dues',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
        migrations.AlterModelTable(
            name='paymentbatch',
            table='payment_batches',
        ),
        migrations.AlterModelTable(
            name='payout',
            table='payouts',
        ),
        migrations.AlterModelTable(
            name='salaryrate',
            table='salary_rates',
        ),
        migrations.AlterModelTable(
            name='setting',
            table='settings',
        ),
        migrations.AlterModelTable(
            name='tariff',
            table='tariffs',
        ),
    ]
