# Generated by Django 6.0.6 on 2026-07-07 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0002_rename_ql_cashentr_fund_id_a847d9_idx_cash_entrie_fund_id_53125c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_status', models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_properties',
            },
        ),
    ]
