# Generated by Django 6.0.6 on 2026-07-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0005_add_timestamps_to_all_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashentry',
            options={'ordering': ['-occurred_at'], 'verbose_name_plural': 'Cash entries'},
        ),
        migrations.AlterModelOptions(
            name='paymentbatch',
            options={'ordering': ['-paid_at'], 'verbose_name_plural': 'Payment batches'},
        ),
    ]
