# Generated by Django 6.0.6 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0006_alter_cashentry_options_alter_paymentbatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='home_number',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
