# Generated by Django 6.0.6 on 2026-07-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0007_userproperty_home_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
