# Generated by Django 6.0.6 on 2026-07-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0008_add_phone_to_user_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperty',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Include country code, e.g. +628123456789', max_length=20),
        ),
    ]
