# Generated by Django 6.0.6 on 2026-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0009_alter_userproperty_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='occupancy_status',
            field=models.CharField(choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant'), ('RENT', 'Rented')], max_length=10),
        ),
    ]
