# Generated by Django 6.0.6 on 2026-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0010_add_receipt_to_payment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbatch',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
