# Generated by Django 6.0.6 on 2026-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0011_receipt_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatch',
            name='nominal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
