# Generated by Django 6.0.6 on 2026-07-07 13:55

import ql.models.payment_batch
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0013_paymentbatch_receipt_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbatch',
            name='receipt',
            field=models.ImageField(blank=True, null=True, storage=ql.storage.get_receipt_storage, upload_to=ql.models.payment_batch._receipt_upload_to),
        ),
    ]
