# Generated by Django 6.0.6 on 2026-07-08 02:50

import django.db.models.deletion
import ql.models.property_tax
import ql.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0014_alter_paymentbatch_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nop', models.CharField(blank=True, default='', help_text='Nomor Objek Pajak', max_length=20)),
                ('land_area', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('building_area', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('attachment', models.ImageField(blank=True, null=True, storage=ql.storage.get_receipt_storage, upload_to=ql.models.property_tax._receipt_upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_taxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_taxes',
            },
        ),
    ]
