# Generated by Django 6.0.6 on 2026-07-10 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0016_alter_propertytax_user_onetoonefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent fund for sub-fund reporting hierarchy. Child funds share the parent pool (not ring-fenced).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ql.fund'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='fund',
            field=models.ForeignKey(blank=True, help_text='Fund this tariff contributes to. Replaces the kind→fund string mapping.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='ql.fund'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CASH_ADVANCE', 'Cash Advance (shortfall)'), ('FEE_PAYABLE', 'Fee Payable (PIC fee)')], max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('borrowed_at', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REPAID', 'Repaid')], default='OPEN', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='ql.fund')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic_fee', models.DecimalField(decimal_places=2, help_text='Agreed PIC compensation. Auto-creates a FEE_PAYABLE Loan on save.', max_digits=15)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='ql.fund')),
                ('pic', models.ForeignKey(help_text='Person in charge responsible for the project end-to-end.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('TRANSFER', 'Internal Transfer')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ql.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(blank=True, choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3, null=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='ql.fund')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='ql.loan')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ql.transaction')),
            ],
            options={
                'db_table': 'transaction_items',
            },
        ),
        migrations.CreateModel(
            name='ItemRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=7)),
                ('transaction_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='ql.transactionitem')),
            ],
            options={
                'db_table': 'item_routines',
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['fund', 'status'], name='loans_fund_id_cef257_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['lender'], name='loans_lender__c79d20_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['direction'], name='transaction_directi_ccf99e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['creator'], name='transaction_creator_ce2265_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['transaction'], name='transaction_transac_163e28_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['fund'], name='transaction_fund_id_bc0037_idx'),
        ),
        migrations.AddIndex(
            model_name='itemroutine',
            index=models.Index(fields=['period'], name='item_routin_period_7c532f_idx'),
        ),
    ]
