# Generated by Django 6.0.6 on 2026-07-10 09:34

import ql.models.receipt
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0017_receipt_fund_parent_tariff_fund_loan_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='url',
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ql.storage.get_receipt_storage, upload_to=ql.models.receipt._receipt_upload_to),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_storage',
            field=models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], default='local', editable=False, help_text='Backend that holds the receipt file.', max_length=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
