# Generated by Django 6.0.6 on 2026-07-11 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0018_remove_receipt_url_receipt_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytax',
            options={'verbose_name_plural': 'Property taxes'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['user', 'start_from']},
        ),
        migrations.RemoveIndex(
            model_name='tariff',
            name='tariffs_user_id_7378e3_idx',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fund',
            name='kind',
            field=models.CharField(choices=[('EARMARKED', 'Earmarked'), ('ROUTINE', 'Routine')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='kind',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly iuran'), ('GARBAGE', 'Garbage iuran')], help_text='Legacy field. Use fund instead.', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['user', 'fund'], name='tariffs_user_id_0a4e30_idx'),
        ),
    ]
