# Generated by Django 6.0.6 on 2026-07-11 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0019_alter_propertytax_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='ql.receipt'),
        ),
    ]
