# Generated by Django 6.0.6 on 2026-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0020_alter_transaction_receipt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_kind_f680c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_batch_i_1122a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentbatch',
            name='payment_bat_user_id_e764fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentbatch',
            name='payment_bat_paid_at_c3564f_idx',
        ),
        migrations.AddField(
            model_name='fund',
            name='color',
            field=models.CharField(blank=True, default='#6b7280', help_text='Hex color used in the dashboard badges, e.g. #22c55e', max_length=20),
        ),
        migrations.RemoveField(
            model_name='paymentbatch',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='paymentbatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentBatch',
        ),
    ]
