# Generated by Django 6.0.6 on 2026-07-11 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0021_remove_payment_payments_kind_f680c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('reason', models.CharField(choices=[('NOT_BILLED', 'Belum ditagih'), ('PROMISED', 'Janji bayar'), ('PAID_CASH', 'Sudah bayar (belum dicatat)'), ('HARDSHIP', 'Kesulitan ekonomi'), ('VACANT', 'Rumah kosong'), ('MOVED', 'Pindah / keluar'), ('DISPUTE', 'Keberatan / sengketa'), ('OTHER', 'Lainnya')], default='NOT_BILLED', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_due_notes', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_notes', to='ql.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'due_notes',
                'constraints': [models.UniqueConstraint(fields=('user', 'fund', 'period'), name='due_notes_unique_user_fund_period')],
            },
        ),
    ]
