# Generated by Django 6.0.6 on 2026-07-11 08:53

import ql.models.due_note
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0022_duenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenote',
            name='proof',
            field=models.ImageField(blank=True, help_text='Optional image proof (e.g. chat screenshot, photo). Auto-compressed on save.', null=True, storage=ql.storage.get_receipt_storage, upload_to=ql.models.due_note._due_note_proof_upload_to),
        ),
    ]
