# Generated by Django 6.0.6 on 2026-07-11 08:57

import django.db.models.deletion
import ql.models.due_note
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0023_duenote_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duenote',
            name='proof',
        ),
        migrations.CreateModel(
            name='DueNoteProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=ql.storage.get_receipt_storage, upload_to=ql.models.due_note._due_note_proof_upload_to)),
                ('due_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='ql.duenote')),
            ],
            options={
                'db_table': 'due_note_proofs',
            },
        ),
    ]
