# Generated by Django 6.0.6 on 2026-07-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0024_remove_duenote_proof_duenoteproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('E-WALLET', 'E-Wallet')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='ql.wallet'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['wallet'], name='transaction_wallet__878fbf_idx'),
        ),
    ]
