# Generated by Django 6.0.6 on 2026-07-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0025_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallets',
        ),
    ]
