# Generated by Django 6.0.6 on 2026-07-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0026_alter_wallet_options_alter_wallet_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionitem',
            name='transaction_wallet__878fbf_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='ql.wallet'),
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='wallet',
        ),
    ]
