# Generated by Django 6.0.6 on 2026-07-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0027_remove_transactionitem_transaction_wallet__878fbf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ql.wallet'),
        ),
    ]
