# Generated by Django 6.0.6 on 2026-07-12 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0028_alter_transaction_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='ql.wallet')),
                ('in_transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ql.transaction')),
                ('out_transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ql.transaction')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='ql.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
