# Generated by Django 6.0.6 on 2026-07-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0029_wallet_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ql.transaction',),
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ql.transaction',),
        ),
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ql.transaction',),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='WalletTransfer',
        ),
    ]
