# Generated by Django 6.0.6 on 2026-07-13 03:25

import django.db.models.deletion
import ql.models.asset
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ql', '0030_expensetransaction_incometransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=50)),
                ('file', models.FileField(blank=True, null=True, storage=ql.storage.get_asset_storage, upload_to=ql.models.asset._asset_upload_to)),
                ('url', models.URLField(blank=True, help_text='External URL, used as a fallback when the file is too large to upload.', max_length=1000, null=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='assets_content_c0e86a_idx'), models.Index(fields=['mime_type'], name='assets_mime_ty_765c27_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(models.Q(('file', ''), _negated=True), ('url__isnull', True)), models.Q(('file', ''), ('url__isnull', False)), _connector='OR'), name='asset_file_xor_url')],
            },
        ),
    ]
