# Generated by Django 6.0.6 on 2026-07-13 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0032_wallettransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='ql.wallettransfer'),
        ),
    ]
