# Generated by Django 6.0.6 on 2026-07-13 08:08

from django.db import migrations


def stamp_existing_legs(apps, schema_editor):
    """Point pre-existing transfer legs at their owning WalletTransfer so they
    are excluded from the income/expense lists and totals."""
    WalletTransfer = apps.get_model('ql', 'WalletTransfer')
    Transaction = apps.get_model('ql', 'Transaction')
    for wt in WalletTransfer.objects.all().iterator():
        Transaction.objects.filter(
            pk__in=[wt.out_transaction_id, wt.in_transaction_id]
        ).update(transfer=wt)


def unstamp_legs(apps, schema_editor):
    Transaction = apps.get_model('ql', 'Transaction')
    Transaction.objects.filter(transfer__isnull=False).update(transfer=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0033_transaction_transfer'),
    ]

    operations = [
        migrations.RunPython(stamp_existing_legs, unstamp_legs),
    ]
