# Generated by Django 6.0.6 on 2026-07-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0034_backfill_transfer_legs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransfer',
            name='in_transaction',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ql.transaction'),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='out_transaction',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ql.transaction'),
        ),
    ]
