# Generated by Django 6.0.6 on 2026-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0035_alter_wallettransfer_in_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ql.transaction',),
        ),
    ]
