# Generated by Django 6.0.6 on 2026-07-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0037_transaction_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_qris',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
