# Generated by Django 6.0.6 on 2026-07-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0038_transaction_is_qris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_qris',
            field=models.BooleanField(default=False),
        ),
    ]
