# Generated by Django 6.0.6 on 2026-07-15 08:32

import django.db.models.deletion
import ql.models.report
import ql.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0040_add_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default='', help_text='Human-readable report title.', max_length=255)),
                ('file', models.FileField(blank=True, help_text='The generated report file (PDF, Excel, etc.)', storage=ql.storage.get_report_storage, upload_to=ql.models.report._report_upload_to)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done')], default='PROCESSING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When generation finished.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, help_text='The fund this report is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ql.fund')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
