# Generated by Django 6.0.6 on 2026-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0041_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
