# Generated by Django 6.0.6 on 2026-07-15 10:55

import ql.models.report
import ql.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0042_report_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was generated from content.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Report body in Markdown. Editable before PDF generation.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, help_text='The generated PDF, rendered from content.', storage=ql.storage.get_report_storage, upload_to=ql.models.report._report_upload_to),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('DRAFT', 'Draft'), ('DONE', 'Done')], default='PROCESSING', max_length=10),
        ),
    ]
