# Generated by Django 6.0.6 on 2026-07-17 04:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0043_report_content_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent fund for sub-fund reporting hierarchy. Child funds share the parent pool (not ring-fenced).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ql.fund'),
        ),
    ]
