# Generated by Django 6.0.6 on 2026-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0045_fund_rebuild_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
