# Generated by Django 6.0.6 on 2026-07-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0046_transactionitem_quantity_integer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wallettransfer',
            table='wallet_transfers',
        ),
    ]
