# Generated by Django 6.0.6 on 2026-07-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ql', '0047_alter_wallettransfer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
